---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u6282940/public_html/
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp web.config $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R atlantis $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R sound $DEPLOYPATH
    - /bin/cp -R tinymce5 $DEPLOYPATH
